# This is a basic workflow to help you get started with Actions
name: PUBLISHING

# Controls when the workflow will run
on:
  # Triggers the workflow on push for tags with name starting on v
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  npm_publishing:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      # Install project
      - name: Install
        run: npm install
      # Re-build project in ./dist
      - name: Re-build
        run: npm run build
      # Publish project into the repository
      - name: Publish
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Archive npm logs after failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: error-npm-logs
          if-no-files-found: ignore
          path: |
            /home/runner/.npm/_logs/
  github_publishing:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
      # Install project
      - name: Install
        run: npm install
      # Re-build project in ./dist
      - name: Re-build
        run: npm run build
      # Publish project into the repository
      - name: Publish
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive npm logs after failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: error-github-logs
          if-no-files-found: ignore
          path: |
            /home/runner/.npm/_logs/
