# This is a basic workflow to help you get started with Actions
name: PUBLISH

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          token: ${{ secrets.NPM_TOKEN }}
          registry-url: 'https://registry.npmjs.org/'
      # Install project
      - name: Install
        run: npm install
      # Re-build project in ./dist
      - name: Re-build
        run: npm run build
      # Publish project into the repository
      #- name: Publish
      #  run: npm run publish
